import { setupApp, pageShell, card, getSession, getState, can } from "./app.js";
import { activateSharedBusiness, createInvitation, resetAllData, restoreTrash, deleteTrash } from "./firebase.js";

const roles = ["administrador", "vendedor", "cajero", "inventario", "consulta"];
function render(state) {
    const session = getSession();
    if (!can("manageCredits")) { window.location.href = "./dashboard.html"; return; }
    const shared = !session.businessId.startsWith("personal:");
    const trashSection = session.role === "propietario" ? `<section class="section-title"><div><h2>Papelera de recuperación</h2><p>Las copias de reinicios se conservan durante 30 días.</p></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Eliminado</th><th>Contenido</th><th>Vence</th><th>Acciones</th></tr></thead><tbody>${(state.papelera || []).length ? state.papelera.map(item => `<tr><td>${new Date(item.eliminadoEn).toLocaleString()}</td><td>${item.resumen.productos} productos · ${item.resumen.ventas} movimientos · ${item.resumen.creditos} créditos</td><td>${new Date(item.venceEn).toLocaleDateString()}</td><td><button class="button button-quiet button-small" data-restore="${item.id}">Restaurar</button> <button class="button button-danger button-small" data-delete-trash="${item.id}">Eliminar definitivamente</button></td></tr>`).join("") : `<tr><td colspan="4"><div class="empty-state">La papelera está vacía.</div></td></tr>`}</tbody></table></div></section>` : "";
    pageShell("Equipo del negocio", "Organiza quién puede vender, cobrar, administrar o consultar.", "usuarios", `<section class="cards">${card("Miembros", state.miembros.length + 1, "Personas asociadas", "")}${card("Negocio", shared ? "Compartido" : "Personal", shared ? "Listo para el equipo" : "Actívalo para invitar", "orange")}${card("Tu rol", session.role, "Nivel de acceso actual", "red")}${card("Permisos", "Por rol", "La navegación se adapta", "blue")}</section>${shared ? "" : `<section class="panel notice-panel"><h2>Activa el negocio compartido</h2><p class="muted">Tus datos actuales se copiarán al espacio compartido sin eliminar tu información personal. Después podrás invitar vendedores y administradores.</p><button id="activateBusiness" class="button button-primary">Activar equipo</button></section>`}<section class="section-title"><div><h2>Invitar miembro</h2><p>La persona recibirá acceso al negocio cuando cree su cuenta con ese correo.</p></div></section><section class="panel"><form id="inviteForm" class="inline-form"><label>Nombre<input id="memberName" placeholder="Nombre del colaborador" required></label><label>Correo<input id="memberEmail" type="email" placeholder="persona@correo.com" required></label><label>Rol<select id="memberRole">${roles.map(role => `<option value="${role}">${role[0].toUpperCase() + role.slice(1)}</option>`).join("")}</select></label><button class="button button-primary" type="submit" ${shared ? "" : "disabled"}>Enviar invitación</button></form><p id="inviteMessage" class="form-message"></p></section><section class="section-title"><div><h2>Miembros registrados</h2><p>Los permisos se aplican al iniciar sesión.</p></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th></tr></thead><tbody><tr><td><strong>${session.name}</strong></td><td>${session.email}</td><td><span class="badge paid">Propietario</span></td></tr>${state.miembros.map(member => `<tr><td>${member.nombre || "Pendiente"}</td><td>${member.correo}</td><td><span class="badge cash">${member.rol}</span></td></tr>`).join("") || `<tr><td colspan="3"><div class="empty-state">Todavía no hay colaboradores invitados.</div></td></tr>`}</tbody></table></div></section>${session.role === "propietario" ? `<section class="section-title"><div><h2>Zona peligrosa</h2><p>Esta acción elimina ventas, créditos, abonos, inventario y gráficos del negocio.</p></div></section><section class="panel danger-panel"><strong>Reiniciar todos los datos</strong><p class="muted">Los miembros y sus permisos se conservarán, pero la operación volverá completamente a cero.</p><button id="resetAllData" class="button button-danger">Borrar todo y reiniciar</button><p id="resetMessage" class="form-message"></p></section>${trashSection}` : ""}`);
    document.querySelector("#activateBusiness")?.addEventListener("click", async () => { const button = document.querySelector("#activateBusiness"); button.disabled = true; button.textContent = "Activando..."; try { await activateSharedBusiness(); window.location.reload(); } catch { button.disabled = false; button.textContent = "No se pudo activar"; } });
    document.querySelector("#inviteForm")?.addEventListener("submit", async event => { event.preventDefault(); const message = document.querySelector("#inviteMessage"); try { await createInvitation(document.querySelector("#memberEmail").value, document.querySelector("#memberRole").value, session.businessId, document.querySelector("#memberName").value); message.textContent = "Invitación preparada. El usuario puede registrarse con ese correo."; } catch { message.textContent = "No se pudo guardar la invitación."; } });
    document.querySelector("#resetAllData")?.addEventListener("click", async () => { if (!confirm("Esto eliminará ventas, créditos, abonos, inventario, historial y gráficos. ¿Continuar?")) return; if (prompt("Escribe REINICIAR para confirmar:") !== "REINICIAR") return; const button = document.querySelector("#resetAllData"); const message = document.querySelector("#resetMessage"); button.disabled = true; button.textContent = "Reiniciando..."; try { await resetAllData(); message.textContent = "El negocio volvió a cero correctamente."; } catch { button.disabled = false; button.textContent = "Borrar todo y reiniciar"; message.textContent = "No se pudo completar el reinicio."; } });
    document.querySelectorAll("[data-restore]").forEach(button => button.addEventListener("click", async () => { if (!confirm("Restaurar esta copia reemplazará el estado actual. ¿Continuar?")) return; try { await restoreTrash(button.dataset.restore); } catch { alert("No se pudo restaurar la copia."); } }));
    document.querySelectorAll("[data-delete-trash]").forEach(button => button.addEventListener("click", async () => { if (!confirm("Esta copia se eliminará definitivamente y no podrá recuperarse. ¿Continuar?")) return; try { await deleteTrash(button.dataset.deleteTrash); } catch { alert("No se pudo eliminar la copia."); } }));
}
pageShell("Cargando...", "Preparando equipo.", "usuarios", ""); setupApp(render);