import { setupApp, pageShell, card, getSession, getState, can } from "./app.js";
import { activateSharedBusiness, createInvitation, saveData } from "./firebase.js";

const roles = ["administrador", "vendedor", "cajero", "inventario", "consulta"];
function render(state) {
    const session = getSession();
    if (!can("manageCredits")) { window.location.href = "./dashboard.html"; return; }
    const shared = !session.businessId.startsWith("personal:");
    pageShell("Equipo del negocio", "Organiza quién puede vender, cobrar, administrar o consultar.", "usuarios", `<section class="cards">${card("Miembros", state.miembros.length + 1, "Personas asociadas", "")}${card("Negocio", shared ? "Compartido" : "Personal", shared ? "Listo para el equipo" : "Actívalo para invitar", "orange")}${card("Tu rol", session.role, "Nivel de acceso actual", "red")}${card("Permisos", "Por rol", "La navegación se adapta", "blue")}</section>${shared ? "" : `<section class="panel notice-panel"><h2>Activa el negocio compartido</h2><p class="muted">Tus datos actuales se copiarán al espacio compartido sin eliminar tu información personal. Después podrás invitar vendedores y administradores.</p><button id="activateBusiness" class="button button-primary">Activar equipo</button></section>`}<section class="section-title"><div><h2>Invitar miembro</h2><p>La persona recibirá acceso al negocio cuando cree su cuenta con ese correo.</p></div></section><section class="panel"><form id="inviteForm" class="inline-form"><label>Nombre<input id="memberName" placeholder="Nombre del colaborador" required></label><label>Correo<input id="memberEmail" type="email" placeholder="persona@correo.com" required></label><label>Rol<select id="memberRole">${roles.map(role => `<option value="${role}">${role[0].toUpperCase() + role.slice(1)}</option>`).join("")}</select></label><button class="button button-primary" type="submit" ${shared ? "" : "disabled"}>Enviar invitación</button></form><p id="inviteMessage" class="form-message"></p></section><section class="section-title"><div><h2>Miembros registrados</h2><p>Los permisos se aplican al iniciar sesión.</p></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th></tr></thead><tbody><tr><td><strong>${session.name}</strong></td><td>${session.email}</td><td><span class="badge paid">Propietario</span></td></tr>${state.miembros.map(member => `<tr><td>${member.nombre || "Pendiente"}</td><td>${member.correo}</td><td><span class="badge cash">${member.rol}</span></td></tr>`).join("") || `<tr><td colspan="3"><div class="empty-state">Todavía no hay colaboradores invitados.</div></td></tr>`}</tbody></table></div></section>`);
    document.querySelector("#activateBusiness")?.addEventListener("click", async () => { const button = document.querySelector("#activateBusiness"); button.disabled = true; button.textContent = "Activando..."; try { await activateSharedBusiness(); window.location.reload(); } catch { button.disabled = false; button.textContent = "No se pudo activar"; } });
    document.querySelector("#inviteForm")?.addEventListener("submit", async event => { event.preventDefault(); const message = document.querySelector("#inviteMessage"); try { await createInvitation(document.querySelector("#memberEmail").value, document.querySelector("#memberRole").value, session.businessId, document.querySelector("#memberName").value); message.textContent = "Invitación preparada. El usuario puede registrarse con ese correo."; } catch { message.textContent = "No se pudo guardar la invitación."; } });
}
pageShell("Cargando...", "Preparando equipo.", "usuarios", ""); setupApp(render);